name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  secretId:
    description: 'Tencent Cloud secret id'
    required: true
  secretKey:
    description: 'Tencent Cloud secret key'
    required: true
  bucket:
    description: 'COS bucket name'
    required: true
  region:
    description: 'COS bucket region'
    required: true
  key:
    description: 'COS Object key name'
    required: false
  content:
    description: 'Content to be uploaded to COS'
    required: trie
outputs:
  url:
    description: 'Cos Location'
runs:
  using: 'node16'
  main: 'dist/index.js'
